name: ara
channels:
  - conda-forge
  - defaults  

dependencies:
  - python=3.12
  - ipykernel
  - pip:
    - ruff==0.14.6
    - pandas==2.3.3
    - numpy==2.3.5
    - matplotlib==3.10.7
    - seaborn==0.13.2
    - openai==2.8.1
    - python-dotenv==1.2.1
    - pydantic==2.12.4
    - instructor==1.13.0
    - sentence-transformers==5.1.2
    - hf_xet==1.2.0
    - plotly==6.5.0
    - nbformat==5.10.4
    - adjustText==1.3.0
    
